name: Swift Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SCHEME_NAME: SRNetworkManager

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - swift: "6.0"
            xcode: "15.2"
            package_file: "Package@swift-6.0.swift"
          - swift: "5.9"
            xcode: "15.0"
            package_file: "Package@swift-5.9.swift"
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Swift ${{ matrix.swift }}
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
        
    - name: Use Correct Package.swift
      run: |
        if [ -f "${{ matrix.package_file }}" ]; then
          cp "${{ matrix.package_file }}" "Package.swift"
        fi
        
    - name: Show Environment
      run: |
        swift --version
        xcodebuild -version
        
    - name: Build Package
      run: swift build -v
        
    - name: Run Tests
      run: swift test -v --enable-code-coverage
        
    - name: Build for iOS
      run: |
        xcodebuild clean build \
          -scheme ${{ env.SCHEME_NAME }} \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=18.2" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES
          
    - name: Generate Coverage Report
      uses: maxep/spm-lcov-action@0.3.1
      
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        swift: true
        swift_project: ${{ env.SCHEME_NAME }}
